[package]
name = "minima-camera"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }
glam = { workspace = true }
